---

- name: epel release
  yum:
    name: epel-release

- name: docker
  yum:
    name: '{{ docker_packages }}'

- name: enable and start
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items: '{{ docker services }}'